/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tappingtest;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wawan
 */
public class FrameBorg extends javax.swing.JDialog {

    public String name;
    int arm, shoulder, neck;
    String blok;
    /**
     * Creates new form FrameBorg
     */
    public FrameBorg() {
        initComponents();
        this.setTitle("Borg Scale");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupArm = new javax.swing.ButtonGroup();
        buttonGroupShoulder = new javax.swing.ButtonGroup();
        buttonGroupNeck = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonArm10 = new javax.swing.JRadioButton();
        jRadioButtonArm9 = new javax.swing.JRadioButton();
        jRadioButtonArm8 = new javax.swing.JRadioButton();
        jRadioButtonArm7 = new javax.swing.JRadioButton();
        jRadioButtonArm6 = new javax.swing.JRadioButton();
        jRadioButtonArm5 = new javax.swing.JRadioButton();
        jRadioButtonArm4 = new javax.swing.JRadioButton();
        jRadioButtonArm3 = new javax.swing.JRadioButton();
        jRadioButtonArm2 = new javax.swing.JRadioButton();
        jRadioButtonArm1 = new javax.swing.JRadioButton();
        jRadioButtonArm0_5 = new javax.swing.JRadioButton();
        jRadioButtonArm0 = new javax.swing.JRadioButton();
        jRadioButtonShoulder7 = new javax.swing.JRadioButton();
        jRadioButtonShoulder6 = new javax.swing.JRadioButton();
        jRadioButtonShoulder5 = new javax.swing.JRadioButton();
        jRadioButtonShoulder4 = new javax.swing.JRadioButton();
        jRadioButtonShoulder3 = new javax.swing.JRadioButton();
        jRadioButtonShoulder2 = new javax.swing.JRadioButton();
        jRadioButtonShoulder1 = new javax.swing.JRadioButton();
        jRadioButtonShoulder0_5 = new javax.swing.JRadioButton();
        jRadioButtonShoulder10 = new javax.swing.JRadioButton();
        jRadioButtonShoulder0 = new javax.swing.JRadioButton();
        jRadioButtonShoulder9 = new javax.swing.JRadioButton();
        jRadioButtonShoulder8 = new javax.swing.JRadioButton();
        jRadioButtonNeck7 = new javax.swing.JRadioButton();
        jRadioButtonNeck6 = new javax.swing.JRadioButton();
        jRadioButtonNeck5 = new javax.swing.JRadioButton();
        jRadioButtonNeck4 = new javax.swing.JRadioButton();
        jRadioButtonNeck3 = new javax.swing.JRadioButton();
        jRadioButtonNeck2 = new javax.swing.JRadioButton();
        jRadioButtonNeck1 = new javax.swing.JRadioButton();
        jRadioButtonNeck0_5 = new javax.swing.JRadioButton();
        jRadioButtonNeck10 = new javax.swing.JRadioButton();
        jRadioButtonNeck0 = new javax.swing.JRadioButton();
        jRadioButtonNeck9 = new javax.swing.JRadioButton();
        jRadioButtonNeck8 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelARM = new javax.swing.JLabel();
        labelARM1 = new javax.swing.JLabel();
        labelARM2 = new javax.swing.JLabel();
        labelARM3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("BORG");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        buttonGroupArm.add(jRadioButtonArm10);
        jRadioButtonArm10.setSelected(true);
        jRadioButtonArm10.setText("10");
        jRadioButtonArm10.setActionCommand("10");

        buttonGroupArm.add(jRadioButtonArm9);
        jRadioButtonArm9.setText("9");
        jRadioButtonArm9.setActionCommand("9");

        buttonGroupArm.add(jRadioButtonArm8);
        jRadioButtonArm8.setText("8");
        jRadioButtonArm8.setActionCommand("8");

        buttonGroupArm.add(jRadioButtonArm7);
        jRadioButtonArm7.setText("7");
        jRadioButtonArm7.setActionCommand("7");

        buttonGroupArm.add(jRadioButtonArm6);
        jRadioButtonArm6.setText("6");
        jRadioButtonArm6.setActionCommand("6");

        buttonGroupArm.add(jRadioButtonArm5);
        jRadioButtonArm5.setText("5");
        jRadioButtonArm5.setActionCommand("5");

        buttonGroupArm.add(jRadioButtonArm4);
        jRadioButtonArm4.setText("4");
        jRadioButtonArm4.setActionCommand("4");

        buttonGroupArm.add(jRadioButtonArm3);
        jRadioButtonArm3.setText("3");
        jRadioButtonArm3.setActionCommand("3");

        buttonGroupArm.add(jRadioButtonArm2);
        jRadioButtonArm2.setText("2");
        jRadioButtonArm2.setActionCommand("2");

        buttonGroupArm.add(jRadioButtonArm1);
        jRadioButtonArm1.setText("1");
        jRadioButtonArm1.setActionCommand("1");

        buttonGroupArm.add(jRadioButtonArm0_5);
        jRadioButtonArm0_5.setText("0.5");
        jRadioButtonArm0_5.setActionCommand("0.5");

        buttonGroupArm.add(jRadioButtonArm0);
        jRadioButtonArm0.setText("0");
        jRadioButtonArm0.setActionCommand("0");

        buttonGroupShoulder.add(jRadioButtonShoulder7);
        jRadioButtonShoulder7.setText("7");
        jRadioButtonShoulder7.setActionCommand("7");

        buttonGroupShoulder.add(jRadioButtonShoulder6);
        jRadioButtonShoulder6.setText("6");
        jRadioButtonShoulder6.setActionCommand("6");

        buttonGroupShoulder.add(jRadioButtonShoulder5);
        jRadioButtonShoulder5.setText("5");
        jRadioButtonShoulder5.setActionCommand("5");

        buttonGroupShoulder.add(jRadioButtonShoulder4);
        jRadioButtonShoulder4.setText("4");
        jRadioButtonShoulder4.setActionCommand("4");

        buttonGroupShoulder.add(jRadioButtonShoulder3);
        jRadioButtonShoulder3.setText("3");
        jRadioButtonShoulder3.setActionCommand("3");

        buttonGroupShoulder.add(jRadioButtonShoulder2);
        jRadioButtonShoulder2.setText("2");
        jRadioButtonShoulder2.setActionCommand("2");

        buttonGroupShoulder.add(jRadioButtonShoulder1);
        jRadioButtonShoulder1.setText("1");
        jRadioButtonShoulder1.setActionCommand("1");

        buttonGroupShoulder.add(jRadioButtonShoulder0_5);
        jRadioButtonShoulder0_5.setText("0.5");
        jRadioButtonShoulder0_5.setActionCommand("0.5");

        buttonGroupShoulder.add(jRadioButtonShoulder10);
        jRadioButtonShoulder10.setSelected(true);
        jRadioButtonShoulder10.setText("10");
        jRadioButtonShoulder10.setActionCommand("10");

        buttonGroupShoulder.add(jRadioButtonShoulder0);
        jRadioButtonShoulder0.setText("0");
        jRadioButtonShoulder0.setActionCommand("0");

        buttonGroupShoulder.add(jRadioButtonShoulder9);
        jRadioButtonShoulder9.setText("9");
        jRadioButtonShoulder9.setActionCommand("9");

        buttonGroupShoulder.add(jRadioButtonShoulder8);
        jRadioButtonShoulder8.setText("8");
        jRadioButtonShoulder8.setActionCommand("8");

        buttonGroupNeck.add(jRadioButtonNeck7);
        jRadioButtonNeck7.setText("7");
        jRadioButtonNeck7.setActionCommand("7");

        buttonGroupNeck.add(jRadioButtonNeck6);
        jRadioButtonNeck6.setText("6");
        jRadioButtonNeck6.setActionCommand("6");

        buttonGroupNeck.add(jRadioButtonNeck5);
        jRadioButtonNeck5.setText("5");
        jRadioButtonNeck5.setActionCommand("5");

        buttonGroupNeck.add(jRadioButtonNeck4);
        jRadioButtonNeck4.setText("4");
        jRadioButtonNeck4.setActionCommand("4");

        buttonGroupNeck.add(jRadioButtonNeck3);
        jRadioButtonNeck3.setText("3");
        jRadioButtonNeck3.setActionCommand("3");

        buttonGroupNeck.add(jRadioButtonNeck2);
        jRadioButtonNeck2.setText("2");
        jRadioButtonNeck2.setActionCommand("2");

        buttonGroupNeck.add(jRadioButtonNeck1);
        jRadioButtonNeck1.setText("1");
        jRadioButtonNeck1.setActionCommand("1");

        buttonGroupNeck.add(jRadioButtonNeck0_5);
        jRadioButtonNeck0_5.setText("0.5");
        jRadioButtonNeck0_5.setActionCommand("0.5");

        buttonGroupNeck.add(jRadioButtonNeck10);
        jRadioButtonNeck10.setSelected(true);
        jRadioButtonNeck10.setText("10");
        jRadioButtonNeck10.setActionCommand("10");

        buttonGroupNeck.add(jRadioButtonNeck0);
        jRadioButtonNeck0.setText("0");
        jRadioButtonNeck0.setActionCommand("0");

        buttonGroupNeck.add(jRadioButtonNeck9);
        jRadioButtonNeck9.setText("9");
        jRadioButtonNeck9.setActionCommand("9");

        buttonGroupNeck.add(jRadioButtonNeck8);
        jRadioButtonNeck8.setText("8");
        jRadioButtonNeck8.setActionCommand("8");

        jLabel2.setText("Very, very strong (almost max.)");

        jLabel3.setText("Very Strong");

        jLabel4.setText("Strong (heavy)");

        jLabel5.setText("Somewhat strong");

        jLabel6.setText("Moderate");

        jLabel7.setText("Weak (light)");

        jLabel8.setText("Very Weak");

        jLabel9.setText("Very, very weak (just noticeable)");

        jLabel10.setText("Nothong at all");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonArm10)
                    .addComponent(jRadioButtonArm9)
                    .addComponent(jRadioButtonArm8)
                    .addComponent(jRadioButtonArm7)
                    .addComponent(jRadioButtonArm6)
                    .addComponent(jRadioButtonArm5)
                    .addComponent(jRadioButtonArm4)
                    .addComponent(jRadioButtonArm3)
                    .addComponent(jRadioButtonArm2)
                    .addComponent(jRadioButtonArm1)
                    .addComponent(jRadioButtonArm0_5)
                    .addComponent(jRadioButtonArm0))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonShoulder10)
                    .addComponent(jRadioButtonShoulder9)
                    .addComponent(jRadioButtonShoulder8)
                    .addComponent(jRadioButtonShoulder7)
                    .addComponent(jRadioButtonShoulder6)
                    .addComponent(jRadioButtonShoulder5)
                    .addComponent(jRadioButtonShoulder4)
                    .addComponent(jRadioButtonShoulder3)
                    .addComponent(jRadioButtonShoulder2)
                    .addComponent(jRadioButtonShoulder1)
                    .addComponent(jRadioButtonShoulder0_5)
                    .addComponent(jRadioButtonShoulder0))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNeck9)
                    .addComponent(jRadioButtonNeck8)
                    .addComponent(jRadioButtonNeck6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNeck10)
                            .addComponent(jRadioButtonNeck7)
                            .addComponent(jRadioButtonNeck5)
                            .addComponent(jRadioButtonNeck4)
                            .addComponent(jRadioButtonNeck3)
                            .addComponent(jRadioButtonNeck2)
                            .addComponent(jRadioButtonNeck1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNeck0_5)
                            .addComponent(jRadioButtonNeck0))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonArm10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm0_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonArm0))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonShoulder10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder0_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonShoulder0))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck10)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonNeck9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonNeck8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonNeck6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck1)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck0_5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNeck0)
                            .addComponent(jLabel10))))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        labelARM.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelARM.setText("ARM");

        labelARM1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelARM1.setText("SHOULDER");

        labelARM2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelARM2.setText("NECK");

        labelARM3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelARM3.setText("Effort");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelARM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelARM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelARM2)
                        .addGap(52, 52, 52)
                        .addComponent(labelARM3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelARM)
                    .addComponent(labelARM1)
                    .addComponent(labelARM2)
                    .addComponent(labelARM3))
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(buttonGroupArm.getSelection().getActionCommand()+"\t"+buttonGroupShoulder.getSelection().getActionCommand()+"\t"+buttonGroupNeck.getSelection().getActionCommand());
        if(!name.isEmpty()){
            try {
                // TODO add your handling code here:
                PrintWriter pw = new PrintWriter(new File("Form Borg "+name+"_"+blok+".csv"));
                StringBuilder sb = new StringBuilder();
                sb.append("Arm, Shoulder, Neck \n");
                sb.append(buttonGroupArm.getSelection().getActionCommand()+","+buttonGroupShoulder.getSelection().getActionCommand()+","+buttonGroupNeck.getSelection().getActionCommand()+"\n");
                pw.write(sb.toString());
                pw.close();
                JOptionPane.showMessageDialog(null, "Save");
            } catch (FileNotFoundException ex) {
                System.out.println(ex.toString());
            }
        } else {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBorg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupArm;
    private javax.swing.ButtonGroup buttonGroupNeck;
    private javax.swing.ButtonGroup buttonGroupShoulder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonArm0;
    private javax.swing.JRadioButton jRadioButtonArm0_5;
    private javax.swing.JRadioButton jRadioButtonArm1;
    private javax.swing.JRadioButton jRadioButtonArm10;
    private javax.swing.JRadioButton jRadioButtonArm2;
    private javax.swing.JRadioButton jRadioButtonArm3;
    private javax.swing.JRadioButton jRadioButtonArm4;
    private javax.swing.JRadioButton jRadioButtonArm5;
    private javax.swing.JRadioButton jRadioButtonArm6;
    private javax.swing.JRadioButton jRadioButtonArm7;
    private javax.swing.JRadioButton jRadioButtonArm8;
    private javax.swing.JRadioButton jRadioButtonArm9;
    private javax.swing.JRadioButton jRadioButtonNeck0;
    private javax.swing.JRadioButton jRadioButtonNeck0_5;
    private javax.swing.JRadioButton jRadioButtonNeck1;
    private javax.swing.JRadioButton jRadioButtonNeck10;
    private javax.swing.JRadioButton jRadioButtonNeck2;
    private javax.swing.JRadioButton jRadioButtonNeck3;
    private javax.swing.JRadioButton jRadioButtonNeck4;
    private javax.swing.JRadioButton jRadioButtonNeck5;
    private javax.swing.JRadioButton jRadioButtonNeck6;
    private javax.swing.JRadioButton jRadioButtonNeck7;
    private javax.swing.JRadioButton jRadioButtonNeck8;
    private javax.swing.JRadioButton jRadioButtonNeck9;
    private javax.swing.JRadioButton jRadioButtonShoulder0;
    private javax.swing.JRadioButton jRadioButtonShoulder0_5;
    private javax.swing.JRadioButton jRadioButtonShoulder1;
    private javax.swing.JRadioButton jRadioButtonShoulder10;
    private javax.swing.JRadioButton jRadioButtonShoulder2;
    private javax.swing.JRadioButton jRadioButtonShoulder3;
    private javax.swing.JRadioButton jRadioButtonShoulder4;
    private javax.swing.JRadioButton jRadioButtonShoulder5;
    private javax.swing.JRadioButton jRadioButtonShoulder6;
    private javax.swing.JRadioButton jRadioButtonShoulder7;
    private javax.swing.JRadioButton jRadioButtonShoulder8;
    private javax.swing.JRadioButton jRadioButtonShoulder9;
    private javax.swing.JLabel labelARM;
    private javax.swing.JLabel labelARM1;
    private javax.swing.JLabel labelARM2;
    private javax.swing.JLabel labelARM3;
    // End of variables declaration//GEN-END:variables
}
