/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tappingtest;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author wawan
 */
public class FrameAwal extends javax.swing.JFrame {

    int no = 1,jumlah = 1;
    int max, distance, width, height, Xcenter, Ycenter, Xpanel, Ypanel;
    long startLeft, startRight, startUp, startBottom; 
    long endLeft, endRight, endUp, endBottom;
    Boolean playLeft, playRight, playUp, playBottom;
    PrintWriter pw;
    StringBuilder sb;
    int Xpanel3, Ypanel5;
    /**
     * Creates new form FrameAwal
     */
    public FrameAwal() {
        playLeft = playRight = playUp = playBottom = false;
        startLeft = startRight = startUp = startBottom = 0; 
        max = 50;
        Xcenter = 290;
        Ycenter = 150;
        Xpanel = 40;
        Ypanel = 120;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Fitt Task Two");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMode = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxBlock = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTrials = new javax.swing.JComboBox<>();
        jButtonBorg = new javax.swing.JButton();
        jButtonDependen = new javax.swing.JButton();
        jButtonIndependen = new javax.swing.JButton();
        jTextFieldCounter = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setText("Mode");

        jComboBoxMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Very Easy", "Easy", "Medium", "Hard" }));
        jComboBoxMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        jLabel3.setText("Time");

        jTextField3.setEditable(false);

        jLabel4.setText("Error");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);

        jLabel5.setText("X");

        jTextField5.setEditable(false);

        jLabel6.setText("Y");

        jLabel7.setText("Block");

        jComboBoxBlock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B1", "B2", "B3" }));

        jLabel8.setText("Trials");

        jComboBoxTrials.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1", "T2", "T3", "T4", "T5" }));
        jComboBoxTrials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrialsActionPerformed(evt);
            }
        });

        jButtonBorg.setText("Borg");
        jButtonBorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorgActionPerformed(evt);
            }
        });

        jButtonDependen.setText("Dependen");
        jButtonDependen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDependenActionPerformed(evt);
            }
        });

        jButtonIndependen.setText("Independen");
        jButtonIndependen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndependenActionPerformed(evt);
            }
        });

        jTextFieldCounter.setEditable(false);

        jLabel9.setText("Counter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBoxBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(73, 73, 73))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxTrials, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jComboBoxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField5)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDependen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIndependen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCounter))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxTrials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIndependen)
                .addGap(18, 18, 18)
                .addComponent(jButtonDependen)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorg)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 240));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 240));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 80));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(240, 80));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBoxModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeActionPerformed
        // TODO add your handling code here:
        if(jComboBoxMode.getSelectedIndex() == 0){
            Xpanel = 40;
            Ypanel = 120;
            jPanel2.setSize(80, 240);  
            jPanel2.setLocation((getWidth()/2)-160, getHeight()/4);
            jPanel3.setSize(80, 240); 
            Xpanel3 = jPanel2.getX()+240+80;
            jPanel3.setLocation(Xpanel3, jPanel2.getY());
            jPanel4.setSize(240, 80);  
            jPanel4.setLocation(jPanel2.getX()+80,jPanel2.getY()-80);
            jPanel5.setSize(240, 80); 
            Ypanel5 = jPanel4.getY()+240+80;
            jPanel5.setLocation(jPanel4.getX(), Ypanel5);
        } else if(jComboBoxMode.getSelectedIndex() == 1){ 
                Xpanel = 25;
                Ypanel = 190;
                jPanel2.setSize(50, 380);
                jPanel2.setLocation((getWidth()/2)-215, getHeight()/6);
                jPanel3.setSize(50, 380);
                Xpanel3 = jPanel2.getX()+380+50;
                jPanel3.setLocation(Xpanel3, jPanel2.getY());
                jPanel4.setSize(380, 50);
                jPanel4.setLocation(jPanel2.getX()+50, jPanel2.getY()-50);
                jPanel5.setSize(380, 50);
                Ypanel5 = jPanel4.getY()+380+50;
                jPanel5.setLocation(jPanel4.getX(), Ypanel5);
        } else if(jComboBoxMode.getSelectedIndex() == 2){  
                Xpanel = 12;
                Ypanel = 210;
                jPanel2.setSize(25, 420);
                jPanel2.setLocation((getWidth()/2)-222, getHeight()/8);
                jPanel3.setSize(25, 420);
                Xpanel3 = jPanel2.getX()+420+25;
                jPanel3.setLocation(Xpanel3, jPanel2.getY());
                jPanel4.setSize(420, 25);
                jPanel4.setLocation(jPanel2.getX()+25, jPanel2.getY()-25);
                jPanel5.setSize(420, 25);
                Ypanel5 = jPanel4.getY()+420+25;
                jPanel5.setLocation(jPanel4.getX(), Ypanel5);
        } else if(jComboBoxMode.getSelectedIndex() == 3){ 
                Xpanel = 5;
                Ypanel = 320;
                jPanel2.setSize(10, 640);
                jPanel2.setLocation((getWidth()/2)-325, getHeight()/14);
                jPanel3.setSize(10, 640);
                Xpanel3 = jPanel2.getX()+640+10;
                jPanel3.setLocation(Xpanel3, jPanel2.getY());
                jPanel4.setSize(640, 10);
                jPanel4.setLocation(jPanel2.getX()+10, jPanel2.getY()-10);
                jPanel5.setSize(640, 10);
                Ypanel5 = jPanel4.getY()+640+10;
                jPanel5.setLocation(jPanel4.getX(), Ypanel5);
                System.out.println(jPanel3.getX() +","+ jPanel3.getY());
                System.out.println(jPanel4.getX() +","+ jPanel4.getY());
                System.out.println(jPanel5.getX() +","+ jPanel5.getY());
        }
    }//GEN-LAST:event_jComboBoxModeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if(! jTextField1.getText().equals("")){
                String nama = jTextField1.getText();
                pw = new PrintWriter(new File(nama+"_"+jComboBoxMode.getSelectedItem()+"_"+jComboBoxBlock.getSelectedItem()+"_"+jComboBoxTrials.getSelectedItem()+".csv"));
                sb = new StringBuilder();
                sb.append("Nomor, Xmouse, Ymouse, error, time, Distance, Width, Height, Index of Difficulty, Xcenter, Ycenter \n");
                playLeft = true;
                jPanel2.setBackground(Color.red);
                if(jComboBoxMode.getSelectedIndex() == 0){ 
                    distance = 240;
                    width = 80;
                    height = 240;
                }
                else if(jComboBoxMode.getSelectedIndex() == 1) { 
                    distance = 380;
                    width = 50;
                    height = 380;
                }
                else if(jComboBoxMode.getSelectedIndex() == 2){ 
                    distance = 420;
                    width = 25;
                    height = 420;
                } else {
                    distance = 640;
                    width = 10;
                    height = 640;
                }
                jTextFieldCounter.setText(""+jumlah);
                jTextField1.setEnabled(false);
//                jComboBoxMode.setEnabled(false);
                jComboBoxBlock.setEnabled(false);
                jComboBoxTrials.setEnabled(false);
                startLeft = 0;
            } else {
                playLeft = playRight = playUp = playBottom = false;
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameAwal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if(playLeft.equals(true)){
            if(startLeft == 0){
                jTextField2.setText(0+" s");
                sb.append(jumlah+","+evt.getXOnScreen()+","+evt.getYOnScreen()+", 0,"+"0 ,"+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+ (jPanel2.getX()+Xpanel) +","+ (jPanel2.getY()+Ypanel) +"\n");
            } else{
                endLeft = System.nanoTime();
                jTextField2.setText((endLeft-startLeft)/1e9+" s");
                sb.append(jumlah+","+evt.getXOnScreen()+","+evt.getYOnScreen()+", 0,"+(endLeft-startLeft)/1e9+","+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+ (jPanel2.getX()+Xpanel) +","+ (jPanel2.getY()+Ypanel) +"\n");
            }
            jTextField3.setText("0");
            jTextFieldCounter.setText(""+jumlah);
            jTextField4.setText(evt.getXOnScreen()+"");
            jTextField5.setText(evt.getYOnScreen()+"");
            jumlah++;
            if(jumlah <= max/2){
                startRight = System.nanoTime();
                jPanel3.setBackground(Color.red);
                jPanel2.setBackground(new java.awt.Color(102,255,255));
                playLeft = false;
                playRight = true;
            } else if(jumlah <= max){
                startUp = 0;
                jPanel4.setBackground(Color.red);
                jPanel2.setBackground(new java.awt.Color(102,255,255));
                jPanel3.setBackground(new java.awt.Color(102,255,255));
                playRight = false;
                playLeft = false;
                playUp = true;
            }else {
                jPanel2.setBackground(new java.awt.Color(102,255,255));
                jPanel3.setBackground(new java.awt.Color(102,255,255));
                jPanel4.setBackground(new java.awt.Color(102,255,255));
                jPanel5.setBackground(new java.awt.Color(102,255,255));
                playLeft = playRight = playUp = playBottom = false;
                jumlah = 0;
                finish();
            }
        } 
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        if(playRight.equals(true)){
            endRight = System.nanoTime();
            jTextField2.setText((endRight-startRight)/1e9+" s");
            jTextField3.setText("0");
            jTextFieldCounter.setText(""+jumlah);
            jTextField4.setText(evt.getXOnScreen()+"");
            jTextField5.setText(evt.getYOnScreen()+"");
            sb.append(jumlah+","+evt.getXOnScreen()+","+evt.getYOnScreen()+", 0,"+(endRight-startRight)/1e9+","+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+ (jPanel3.getX()+Xpanel) +","+ (jPanel3.getY()+Ypanel) +"\n");
            jumlah++;
            if(jumlah <= max/2){
                startLeft = System.nanoTime();
                jPanel2.setBackground(Color.red);
                jPanel3.setBackground(new java.awt.Color(102,255,255));
                playLeft = true;
                playRight = false;
            } else if(jumlah <= max){
                jPanel4.setBackground(Color.red);
                jPanel2.setBackground(new java.awt.Color(102,255,255));
                jPanel3.setBackground(new java.awt.Color(102,255,255));
                playRight = false;
                playLeft = false;
                playUp = true;
            } else {
                jPanel2.setBackground(new java.awt.Color(102,255,255));
                jPanel3.setBackground(new java.awt.Color(102,255,255));
                jPanel4.setBackground(new java.awt.Color(102,255,255));
                jPanel5.setBackground(new java.awt.Color(102,255,255));
                playLeft = playRight = playUp = playBottom = false;
                jumlah = 0;
                finish();
            }
            
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        if(playUp.equals(true)){
            if(startUp == 0){
                jTextField2.setText("0 s");
                sb.append(jumlah+","+evt.getXOnScreen()+","+evt.getYOnScreen()+", 0,"+"0 ,"+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+ (jPanel4.getX()+Ypanel) +","+ (jPanel4.getY()+Xpanel) +"\n");
            } else{
                endUp = System.nanoTime();
                jTextField2.setText((endUp-startUp)/1e9+" s");
                sb.append(jumlah+","+evt.getXOnScreen()+","+evt.getYOnScreen()+", 0,"+(endUp-startUp)/1e9+","+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+ (jPanel4.getX()+Ypanel) +","+ (jPanel4.getY()+Xpanel) +"\n");
            }
            jTextField3.setText("0");
            jTextFieldCounter.setText(""+jumlah);
            jTextField4.setText(evt.getXOnScreen()+"");
            jTextField5.setText(evt.getYOnScreen()+"");
            if(jumlah != max/2){jumlah++;}
            if(jumlah <= max){
                startBottom = System.nanoTime();
                jPanel5.setBackground(Color.red);
                jPanel4.setBackground(new java.awt.Color(102,255,255));
                playUp = false;
                playBottom = true;
            } else {
                jPanel4.setBackground(new java.awt.Color(102,255,255));
                playLeft = playRight = playUp = playBottom = false;
                jumlah = 0;
                finish();
            }
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        if(playBottom.equals(true)){
            endBottom = System.nanoTime();
            jTextField2.setText((endBottom-startBottom)/1e9+" s");
            jTextField3.setText("0");
            jTextFieldCounter.setText(""+jumlah);
            jTextField4.setText(evt.getXOnScreen()+"");
            jTextField5.setText(evt.getYOnScreen()+"");
            sb.append(jumlah+","+evt.getXOnScreen()+","+evt.getYOnScreen()+", 0,"+(endBottom-startBottom)/1e9+","+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+ (jPanel5.getX()+Ypanel) +","+ (jPanel5.getY()+Xpanel) +"\n");
            jumlah++;
            if(jumlah <= max){
                startUp = System.nanoTime();
                jPanel4.setBackground(Color.red);
                jPanel5.setBackground(new java.awt.Color(102,255,255));
                playUp = true;
                playBottom = false;
            } else {
                jPanel5.setBackground(new java.awt.Color(102,255,255));
                playLeft = playRight = playUp = playBottom = false;
                jumlah = 0;
                finish();
            }
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(playLeft.equals(true) || playRight.equals(true) || playUp.equals(true) || playBottom.equals(true)){
            jTextField3.setText("1");
            jTextField4.setText(evt.getXOnScreen()+"");
            jTextField5.setText(evt.getYOnScreen()+"");
            if(playLeft.equals(true)){
                Xcenter = jPanel2.getX();
                Ycenter = jPanel2.getY();
            } else if(playRight.equals(true)){
                Xcenter = jPanel3.getX();
                Ycenter = jPanel3.getY();
            } else if(playUp.equals(true)){
                Xcenter = jPanel4.getX();
                Ycenter = jPanel4.getY();
            } else if(playBottom.equals(true)){
                Xcenter = jPanel5.getX();
                Ycenter = jPanel5.getY();
            }
            double waktu = 0;
            if(playLeft.equals(true)){
                endLeft  = System.nanoTime();
                waktu = (endLeft-startLeft)/1e9;
            } else if(playRight.equals(true)){
                endRight = System.nanoTime();
                waktu = (endRight-startRight)/1e9;
            } else if(playUp.equals(true)){
                endUp = System.nanoTime();
                waktu = (endUp-startUp)/1e9;
            } else if(playBottom.equals(true)){
                endBottom = System.nanoTime();
                waktu = (endBottom-startBottom)/1e9;
            }
            
            sb.append("error ,"+evt.getXOnScreen()+","+evt.getYOnScreen()+",1,"+waktu+","+distance+","+width+","+height+","+jComboBoxMode.getSelectedIndex()+","+Xcenter+","+Ycenter+"\n");
            if(jumlah > max){
                jPanel2.setBackground(new java.awt.Color(102,255,255));
                jPanel3.setBackground(new java.awt.Color(102,255,255));
                jPanel4.setBackground(new java.awt.Color(102,255,255));
                jPanel5.setBackground(new java.awt.Color(102,255,255));
                playLeft = playRight = playUp = playBottom = false;
                jumlah = 1;
                finish();
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void jComboBoxTrialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrialsActionPerformed

    private void jButtonBorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorgActionPerformed
        // TODO add your handling code here:
        FrameBorg frame = new FrameBorg();
        frame.blok = (String) jComboBoxBlock.getSelectedItem();
        frame.name = jTextField1.getText();
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonBorgActionPerformed

    private void jButtonDependenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDependenActionPerformed
        // TODO add your handling code here:
        FrameDependen frame = new FrameDependen();
        frame.name = jTextField1.getText();
        frame.blok = (String) jComboBoxBlock.getSelectedItem();
        frame.mode = (String) jComboBoxMode.getSelectedItem();
        frame.trial = (String) jComboBoxTrials.getSelectedItem();
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonDependenActionPerformed

    private void jButtonIndependenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndependenActionPerformed
        // TODO add your handling code here:
        FrameIndependen frame = new FrameIndependen();
        frame.name = jTextField1.getText();
        frame.blok = (String) jComboBoxBlock.getSelectedItem();
        frame.mode = (String) jComboBoxMode.getSelectedItem();
        frame.trial = (String) jComboBoxTrials.getSelectedItem();
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonIndependenActionPerformed

    public void finish(){
        pw.write(sb.toString());
        pw.close();
        jTextField1.setEnabled(true);
        jComboBoxMode.setEnabled(true);
        jComboBoxBlock.setEnabled(true);
        jComboBoxTrials.setEnabled(true);
        FrameIndependen frameI = new FrameIndependen();
        frameI.name = jTextField1.getText();
        frameI.blok = (String) jComboBoxBlock.getSelectedItem();
        frameI.mode = (String) jComboBoxMode.getSelectedItem();
        frameI.trial = (String) jComboBoxTrials.getSelectedItem();
        frameI.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAwal().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorg;
    private javax.swing.JButton jButtonDependen;
    private javax.swing.JButton jButtonIndependen;
    private javax.swing.JComboBox<String> jComboBoxBlock;
    private javax.swing.JComboBox<String> jComboBoxMode;
    private javax.swing.JComboBox<String> jComboBoxTrials;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCounter;
    // End of variables declaration//GEN-END:variables
}
