/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tappingtest;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wawan
 */
public class FrameForm extends javax.swing.JFrame {

    public String name;
    /**
     * Creates new form FrameForm
     */
    public FrameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGerakan = new javax.swing.ButtonGroup();
        buttonGroupKehalusan = new javax.swing.ButtonGroup();
        buttonGroupUsaha = new javax.swing.ButtonGroup();
        buttonGroupAkurasi = new javax.swing.ButtonGroup();
        buttonGroupKecepatan = new javax.swing.ButtonGroup();
        buttonGroupKenyamanan = new javax.swing.ButtonGroup();
        buttonGroupKeseluruhan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelGerakan = new javax.swing.JPanel();
        labelGerakan = new javax.swing.JLabel();
        radioButtonGerakan1 = new javax.swing.JRadioButton();
        radioButtonGerakan2 = new javax.swing.JRadioButton();
        radioButtonGerakan3 = new javax.swing.JRadioButton();
        radioButtonGerakan4 = new javax.swing.JRadioButton();
        radioButtonGerakan5 = new javax.swing.JRadioButton();
        radioButtonGerakan6 = new javax.swing.JRadioButton();
        radioButtonGerakan7 = new javax.swing.JRadioButton();
        panelKehalusan = new javax.swing.JPanel();
        labelKehalusan = new javax.swing.JLabel();
        radioButtonKehalusan6 = new javax.swing.JRadioButton();
        radioButtonKehalusan2 = new javax.swing.JRadioButton();
        radioButtonKehalusan7 = new javax.swing.JRadioButton();
        radioButtonKehalusan1 = new javax.swing.JRadioButton();
        radioButtonKehalusan5 = new javax.swing.JRadioButton();
        radioButtonKehalusan4 = new javax.swing.JRadioButton();
        radioButtonKehalusan3 = new javax.swing.JRadioButton();
        panelUsaha = new javax.swing.JPanel();
        labelUsaha = new javax.swing.JLabel();
        radioButtonUsaha1 = new javax.swing.JRadioButton();
        radioButtonUsaha2 = new javax.swing.JRadioButton();
        radioButtonUsaha3 = new javax.swing.JRadioButton();
        radioButtonUsaha4 = new javax.swing.JRadioButton();
        radioButtonUsaha5 = new javax.swing.JRadioButton();
        radioButtonUsaha6 = new javax.swing.JRadioButton();
        radioButtonUsaha7 = new javax.swing.JRadioButton();
        panelAkurasi = new javax.swing.JPanel();
        labelAkurasi = new javax.swing.JLabel();
        radioButtonAkurasi1 = new javax.swing.JRadioButton();
        radioButtonAkurasi2 = new javax.swing.JRadioButton();
        radioButtonAkurasi3 = new javax.swing.JRadioButton();
        radioButtonAkurasi4 = new javax.swing.JRadioButton();
        radioButtonAkurasi5 = new javax.swing.JRadioButton();
        radioButtonAkurasi6 = new javax.swing.JRadioButton();
        radioButtonAkurasi7 = new javax.swing.JRadioButton();
        panelKenyamanan = new javax.swing.JPanel();
        labelKenyamanan = new javax.swing.JLabel();
        radioButtonKenyamanan1 = new javax.swing.JRadioButton();
        radioButtonKenyamanan2 = new javax.swing.JRadioButton();
        radioButtonKenyamanan3 = new javax.swing.JRadioButton();
        radioButtonKenyamanan4 = new javax.swing.JRadioButton();
        radioButtonKenyamanan5 = new javax.swing.JRadioButton();
        radioButtonKenyamanan6 = new javax.swing.JRadioButton();
        radioButtonKenyamanan7 = new javax.swing.JRadioButton();
        panelKecepatan = new javax.swing.JPanel();
        labelKecepatan = new javax.swing.JLabel();
        radioButtonKecepatan1 = new javax.swing.JRadioButton();
        radioButtonKecepatan2 = new javax.swing.JRadioButton();
        radioButtonKecepatan3 = new javax.swing.JRadioButton();
        radioButtonKecepatan4 = new javax.swing.JRadioButton();
        radioButtonKecepatan6 = new javax.swing.JRadioButton();
        radioButtonKecepatan7 = new javax.swing.JRadioButton();
        radioButtonKecepatan5 = new javax.swing.JRadioButton();
        panelKeseluruhan = new javax.swing.JPanel();
        labelKeseluruhan = new javax.swing.JLabel();
        radioButtonKeseluruhan1 = new javax.swing.JRadioButton();
        radioButtonKeseluruhan2 = new javax.swing.JRadioButton();
        radioButtonKeseluruhan3 = new javax.swing.JRadioButton();
        radioButtonKeseluruhan4 = new javax.swing.JRadioButton();
        radioButtonKeseluruhan5 = new javax.swing.JRadioButton();
        radioButtonKeseluruhan6 = new javax.swing.JRadioButton();
        radioButtonKeseluruhan7 = new javax.swing.JRadioButton();
        labelNegatif = new javax.swing.JLabel();
        labelPositif = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        panelGerakan.setBackground(new java.awt.Color(255, 255, 153));

        labelGerakan.setText("Gerakan :");

        radioButtonGerakan1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan1);
        radioButtonGerakan1.setSelected(true);
        radioButtonGerakan1.setText("1");
        radioButtonGerakan1.setActionCommand("1");

        radioButtonGerakan2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan2);
        radioButtonGerakan2.setText("2");
        radioButtonGerakan2.setActionCommand("2");

        radioButtonGerakan3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan3);
        radioButtonGerakan3.setText("3");
        radioButtonGerakan3.setActionCommand("3");

        radioButtonGerakan4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan4);
        radioButtonGerakan4.setText("4");
        radioButtonGerakan4.setActionCommand("4");

        radioButtonGerakan5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan5);
        radioButtonGerakan5.setText("5");
        radioButtonGerakan5.setActionCommand("5");

        radioButtonGerakan6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan6);
        radioButtonGerakan6.setText("6");
        radioButtonGerakan6.setActionCommand("6");

        radioButtonGerakan7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGerakan.add(radioButtonGerakan7);
        radioButtonGerakan7.setText("7");
        radioButtonGerakan7.setActionCommand("7");

        javax.swing.GroupLayout panelGerakanLayout = new javax.swing.GroupLayout(panelGerakan);
        panelGerakan.setLayout(panelGerakanLayout);
        panelGerakanLayout.setHorizontalGroup(
            panelGerakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGerakanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGerakan)
                .addGap(40, 40, 40)
                .addComponent(radioButtonGerakan1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonGerakan2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonGerakan3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonGerakan4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonGerakan5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonGerakan6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonGerakan7)
                .addGap(24, 24, 24))
        );
        panelGerakanLayout.setVerticalGroup(
            panelGerakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGerakanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGerakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGerakan)
                    .addComponent(radioButtonGerakan1)
                    .addComponent(radioButtonGerakan2)
                    .addComponent(radioButtonGerakan3)
                    .addComponent(radioButtonGerakan4)
                    .addComponent(radioButtonGerakan5)
                    .addComponent(radioButtonGerakan6)
                    .addComponent(radioButtonGerakan7)))
        );

        panelKehalusan.setBackground(new java.awt.Color(255, 255, 153));

        labelKehalusan.setText("Kehalusan :");

        radioButtonKehalusan6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan6);
        radioButtonKehalusan6.setText("6");
        radioButtonKehalusan6.setActionCommand("6");

        radioButtonKehalusan2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan2);
        radioButtonKehalusan2.setText("2");
        radioButtonKehalusan2.setActionCommand("2");

        radioButtonKehalusan7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan7);
        radioButtonKehalusan7.setText("7");
        radioButtonKehalusan7.setActionCommand("7");

        radioButtonKehalusan1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan1);
        radioButtonKehalusan1.setSelected(true);
        radioButtonKehalusan1.setText("1");
        radioButtonKehalusan1.setActionCommand("1");

        radioButtonKehalusan5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan5);
        radioButtonKehalusan5.setText("5");
        radioButtonKehalusan5.setActionCommand("5");

        radioButtonKehalusan4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan4);
        radioButtonKehalusan4.setText("4");
        radioButtonKehalusan4.setActionCommand("4");
        radioButtonKehalusan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonKehalusan4ActionPerformed(evt);
            }
        });

        radioButtonKehalusan3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKehalusan.add(radioButtonKehalusan3);
        radioButtonKehalusan3.setText("3");
        radioButtonKehalusan3.setActionCommand("3");

        javax.swing.GroupLayout panelKehalusanLayout = new javax.swing.GroupLayout(panelKehalusan);
        panelKehalusan.setLayout(panelKehalusanLayout);
        panelKehalusanLayout.setHorizontalGroup(
            panelKehalusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKehalusanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKehalusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(radioButtonKehalusan1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKehalusan2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKehalusan3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKehalusan4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKehalusan5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKehalusan6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKehalusan7)
                .addGap(23, 23, 23))
        );
        panelKehalusanLayout.setVerticalGroup(
            panelKehalusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKehalusanLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelKehalusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonKehalusan1)
                    .addComponent(radioButtonKehalusan2)
                    .addComponent(radioButtonKehalusan3)
                    .addComponent(radioButtonKehalusan4)
                    .addComponent(radioButtonKehalusan5)
                    .addComponent(radioButtonKehalusan6)
                    .addComponent(radioButtonKehalusan7)
                    .addComponent(labelKehalusan)))
        );

        panelUsaha.setBackground(new java.awt.Color(255, 255, 153));

        labelUsaha.setText("Usaha :");

        radioButtonUsaha1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha1);
        radioButtonUsaha1.setSelected(true);
        radioButtonUsaha1.setText("1");
        radioButtonUsaha1.setActionCommand("1");

        radioButtonUsaha2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha2);
        radioButtonUsaha2.setText("2");
        radioButtonUsaha2.setActionCommand("2");

        radioButtonUsaha3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha3);
        radioButtonUsaha3.setText("3");
        radioButtonUsaha3.setActionCommand("3");

        radioButtonUsaha4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha4);
        radioButtonUsaha4.setText("4");
        radioButtonUsaha4.setActionCommand("4");
        radioButtonUsaha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonUsaha4ActionPerformed(evt);
            }
        });

        radioButtonUsaha5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha5);
        radioButtonUsaha5.setText("5");
        radioButtonUsaha5.setActionCommand("5");

        radioButtonUsaha6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha6);
        radioButtonUsaha6.setText("6");
        radioButtonUsaha6.setActionCommand("6");

        radioButtonUsaha7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupUsaha.add(radioButtonUsaha7);
        radioButtonUsaha7.setText("7");
        radioButtonUsaha7.setActionCommand("7");

        javax.swing.GroupLayout panelUsahaLayout = new javax.swing.GroupLayout(panelUsaha);
        panelUsaha.setLayout(panelUsahaLayout);
        panelUsahaLayout.setHorizontalGroup(
            panelUsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsahaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsaha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonUsaha1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonUsaha2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonUsaha3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonUsaha4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonUsaha5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonUsaha6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonUsaha7)
                .addGap(25, 25, 25))
        );
        panelUsahaLayout.setVerticalGroup(
            panelUsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsahaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsahaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsaha)
                    .addComponent(radioButtonUsaha1)
                    .addComponent(radioButtonUsaha2)
                    .addComponent(radioButtonUsaha3)
                    .addComponent(radioButtonUsaha4)
                    .addComponent(radioButtonUsaha5)
                    .addComponent(radioButtonUsaha6)
                    .addComponent(radioButtonUsaha7)))
        );

        panelAkurasi.setBackground(new java.awt.Color(255, 255, 153));

        labelAkurasi.setText("Akurasi :");

        radioButtonAkurasi1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi1);
        radioButtonAkurasi1.setSelected(true);
        radioButtonAkurasi1.setText("1");
        radioButtonAkurasi1.setActionCommand("1");
        radioButtonAkurasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAkurasi1ActionPerformed(evt);
            }
        });

        radioButtonAkurasi2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi2);
        radioButtonAkurasi2.setText("2");
        radioButtonAkurasi2.setActionCommand("2");

        radioButtonAkurasi3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi3);
        radioButtonAkurasi3.setText("3");
        radioButtonAkurasi3.setActionCommand("3");

        radioButtonAkurasi4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi4);
        radioButtonAkurasi4.setText("4");
        radioButtonAkurasi4.setActionCommand("4");
        radioButtonAkurasi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAkurasi4ActionPerformed(evt);
            }
        });

        radioButtonAkurasi5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi5);
        radioButtonAkurasi5.setText("5");
        radioButtonAkurasi5.setActionCommand("5");

        radioButtonAkurasi6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi6);
        radioButtonAkurasi6.setText("6");
        radioButtonAkurasi6.setActionCommand("6");

        radioButtonAkurasi7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAkurasi.add(radioButtonAkurasi7);
        radioButtonAkurasi7.setText("7");
        radioButtonAkurasi7.setActionCommand("7");

        javax.swing.GroupLayout panelAkurasiLayout = new javax.swing.GroupLayout(panelAkurasi);
        panelAkurasi.setLayout(panelAkurasiLayout);
        panelAkurasiLayout.setHorizontalGroup(
            panelAkurasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkurasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAkurasi)
                .addGap(43, 43, 43)
                .addComponent(radioButtonAkurasi1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonAkurasi2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonAkurasi3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonAkurasi4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonAkurasi5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonAkurasi6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonAkurasi7)
                .addGap(24, 24, 24))
        );
        panelAkurasiLayout.setVerticalGroup(
            panelAkurasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkurasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAkurasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAkurasi)
                    .addComponent(radioButtonAkurasi1)
                    .addComponent(radioButtonAkurasi2)
                    .addComponent(radioButtonAkurasi3)
                    .addComponent(radioButtonAkurasi4)
                    .addComponent(radioButtonAkurasi5)
                    .addComponent(radioButtonAkurasi6)
                    .addComponent(radioButtonAkurasi7)))
        );

        panelKenyamanan.setBackground(new java.awt.Color(255, 255, 153));

        labelKenyamanan.setText("Kenyamanan :");

        radioButtonKenyamanan1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan1);
        radioButtonKenyamanan1.setSelected(true);
        radioButtonKenyamanan1.setText("1");
        radioButtonKenyamanan1.setActionCommand("1");

        radioButtonKenyamanan2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan2);
        radioButtonKenyamanan2.setText("2");
        radioButtonKenyamanan2.setActionCommand("2");

        radioButtonKenyamanan3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan3);
        radioButtonKenyamanan3.setText("3");
        radioButtonKenyamanan3.setActionCommand("3");

        radioButtonKenyamanan4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan4);
        radioButtonKenyamanan4.setText("4");
        radioButtonKenyamanan4.setActionCommand("4");
        radioButtonKenyamanan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonKenyamanan4ActionPerformed(evt);
            }
        });

        radioButtonKenyamanan5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan5);
        radioButtonKenyamanan5.setText("5");
        radioButtonKenyamanan5.setActionCommand("5");

        radioButtonKenyamanan6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan6);
        radioButtonKenyamanan6.setText("6");
        radioButtonKenyamanan6.setActionCommand("6");

        radioButtonKenyamanan7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKenyamanan.add(radioButtonKenyamanan7);
        radioButtonKenyamanan7.setText("7");
        radioButtonKenyamanan7.setActionCommand("7");

        javax.swing.GroupLayout panelKenyamananLayout = new javax.swing.GroupLayout(panelKenyamanan);
        panelKenyamanan.setLayout(panelKenyamananLayout);
        panelKenyamananLayout.setHorizontalGroup(
            panelKenyamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKenyamananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKenyamanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonKenyamanan1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKenyamanan2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKenyamanan3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKenyamanan4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKenyamanan5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKenyamanan6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKenyamanan7)
                .addGap(25, 25, 25))
        );
        panelKenyamananLayout.setVerticalGroup(
            panelKenyamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKenyamananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelKenyamananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKenyamanan)
                    .addComponent(radioButtonKenyamanan1)
                    .addComponent(radioButtonKenyamanan2)
                    .addComponent(radioButtonKenyamanan3)
                    .addComponent(radioButtonKenyamanan4)
                    .addComponent(radioButtonKenyamanan5)
                    .addComponent(radioButtonKenyamanan6)
                    .addComponent(radioButtonKenyamanan7)))
        );

        panelKecepatan.setBackground(new java.awt.Color(255, 255, 153));

        labelKecepatan.setText("Kecepatan :");

        radioButtonKecepatan1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan1);
        radioButtonKecepatan1.setSelected(true);
        radioButtonKecepatan1.setText("1");
        radioButtonKecepatan1.setActionCommand("1");

        radioButtonKecepatan2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan2);
        radioButtonKecepatan2.setText("2");
        radioButtonKecepatan2.setActionCommand("2");

        radioButtonKecepatan3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan3);
        radioButtonKecepatan3.setText("3");
        radioButtonKecepatan3.setActionCommand("3");

        radioButtonKecepatan4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan4);
        radioButtonKecepatan4.setText("4");
        radioButtonKecepatan4.setActionCommand("4");
        radioButtonKecepatan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonKecepatan4ActionPerformed(evt);
            }
        });

        radioButtonKecepatan6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan6);
        radioButtonKecepatan6.setText("6");
        radioButtonKecepatan6.setActionCommand("6");

        radioButtonKecepatan7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan7);
        radioButtonKecepatan7.setText("7");
        radioButtonKecepatan7.setActionCommand("7");

        radioButtonKecepatan5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKecepatan.add(radioButtonKecepatan5);
        radioButtonKecepatan5.setText("5");
        radioButtonKecepatan5.setActionCommand("5");

        javax.swing.GroupLayout panelKecepatanLayout = new javax.swing.GroupLayout(panelKecepatan);
        panelKecepatan.setLayout(panelKecepatanLayout);
        panelKecepatanLayout.setHorizontalGroup(
            panelKecepatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKecepatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKecepatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonKecepatan1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKecepatan2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKecepatan3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKecepatan4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKecepatan5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKecepatan6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKecepatan7)
                .addGap(16, 16, 16))
        );
        panelKecepatanLayout.setVerticalGroup(
            panelKecepatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKecepatanLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(panelKecepatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKecepatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonKecepatan3)
                        .addComponent(radioButtonKecepatan4)
                        .addComponent(radioButtonKecepatan5)
                        .addComponent(radioButtonKecepatan6)
                        .addComponent(radioButtonKecepatan7)
                        .addComponent(radioButtonKecepatan1)
                        .addComponent(radioButtonKecepatan2))
                    .addComponent(labelKecepatan)))
        );

        panelKeseluruhan.setBackground(new java.awt.Color(255, 255, 153));

        labelKeseluruhan.setText("Keseluruhan :");

        radioButtonKeseluruhan1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan1);
        radioButtonKeseluruhan1.setSelected(true);
        radioButtonKeseluruhan1.setText("1");
        radioButtonKeseluruhan1.setActionCommand("1");

        radioButtonKeseluruhan2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan2);
        radioButtonKeseluruhan2.setText("2");
        radioButtonKeseluruhan2.setActionCommand("2");

        radioButtonKeseluruhan3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan3);
        radioButtonKeseluruhan3.setText("3");
        radioButtonKeseluruhan3.setActionCommand("3");

        radioButtonKeseluruhan4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan4);
        radioButtonKeseluruhan4.setText("4");
        radioButtonKeseluruhan4.setActionCommand("4");
        radioButtonKeseluruhan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonKeseluruhan4ActionPerformed(evt);
            }
        });

        radioButtonKeseluruhan5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan5);
        radioButtonKeseluruhan5.setText("5");
        radioButtonKeseluruhan5.setActionCommand("5");

        radioButtonKeseluruhan6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan6);
        radioButtonKeseluruhan6.setText("6");
        radioButtonKeseluruhan6.setActionCommand("6");

        radioButtonKeseluruhan7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupKeseluruhan.add(radioButtonKeseluruhan7);
        radioButtonKeseluruhan7.setText("7");
        radioButtonKeseluruhan7.setActionCommand("7");

        javax.swing.GroupLayout panelKeseluruhanLayout = new javax.swing.GroupLayout(panelKeseluruhan);
        panelKeseluruhan.setLayout(panelKeseluruhanLayout);
        panelKeseluruhanLayout.setHorizontalGroup(
            panelKeseluruhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeseluruhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKeseluruhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonKeseluruhan1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKeseluruhan2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKeseluruhan3)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKeseluruhan4)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKeseluruhan5)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKeseluruhan6)
                .addGap(18, 18, 18)
                .addComponent(radioButtonKeseluruhan7)
                .addGap(25, 25, 25))
        );
        panelKeseluruhanLayout.setVerticalGroup(
            panelKeseluruhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeseluruhanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelKeseluruhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKeseluruhan)
                    .addComponent(radioButtonKeseluruhan1)
                    .addComponent(radioButtonKeseluruhan2)
                    .addComponent(radioButtonKeseluruhan3)
                    .addComponent(radioButtonKeseluruhan4)
                    .addComponent(radioButtonKeseluruhan5)
                    .addComponent(radioButtonKeseluruhan6)
                    .addComponent(radioButtonKeseluruhan7)))
        );

        labelNegatif.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelNegatif.setText("Negatif");

        labelPositif.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelPositif.setText("Positif");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGerakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUsaha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAkurasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelKenyamanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelKeseluruhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(labelNegatif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPositif)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelKehalusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelKecepatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNegatif)
                    .addComponent(labelPositif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGerakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKehalusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAkurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKecepatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelKenyamanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKeseluruhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelJudul.setText("Independen");
        labelJudul.setToolTipText("");
        labelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonCancel.setText("Cancel");

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(buttonCancel)
                        .addGap(80, 80, 80)
                        .addComponent(buttonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonKehalusan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonKehalusan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonKehalusan4ActionPerformed

    private void radioButtonUsaha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonUsaha4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonUsaha4ActionPerformed

    private void radioButtonAkurasi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAkurasi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAkurasi4ActionPerformed

    private void radioButtonKecepatan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonKecepatan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonKecepatan4ActionPerformed

    private void radioButtonKenyamanan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonKenyamanan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonKenyamanan4ActionPerformed

    private void radioButtonKeseluruhan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonKeseluruhan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonKeseluruhan4ActionPerformed

    private void radioButtonAkurasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAkurasi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAkurasi1ActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        try {
            // TODO add your handling code here:
            PrintWriter pw = new PrintWriter(new File("Form Independen "+name+".csv"));
            StringBuilder sb = new StringBuilder();
            sb.append("Gerakan, Kehalusan, Usaha, Akurasi, Kecepatan, Kenyamanan, Keseluruhan \n");
            sb.append(buttonGroupGerakan.getSelection().getActionCommand()+",");
            sb.append(buttonGroupKehalusan.getSelection().getActionCommand()+",");
            sb.append(buttonGroupUsaha.getSelection().getActionCommand()+",");
            sb.append(buttonGroupAkurasi.getSelection().getActionCommand()+",");
            sb.append(buttonGroupKecepatan.getSelection().getActionCommand()+",");
            sb.append(buttonGroupKenyamanan.getSelection().getActionCommand()+",");
            sb.append(buttonGroupKeseluruhan.getSelection().getActionCommand()+"\n");
            pw.write(sb.toString());
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.ButtonGroup buttonGroupAkurasi;
    private javax.swing.ButtonGroup buttonGroupGerakan;
    private javax.swing.ButtonGroup buttonGroupKecepatan;
    private javax.swing.ButtonGroup buttonGroupKehalusan;
    private javax.swing.ButtonGroup buttonGroupKenyamanan;
    private javax.swing.ButtonGroup buttonGroupKeseluruhan;
    private javax.swing.ButtonGroup buttonGroupUsaha;
    private javax.swing.JButton buttonSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAkurasi;
    private javax.swing.JLabel labelGerakan;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKecepatan;
    private javax.swing.JLabel labelKehalusan;
    private javax.swing.JLabel labelKenyamanan;
    private javax.swing.JLabel labelKeseluruhan;
    private javax.swing.JLabel labelNegatif;
    private javax.swing.JLabel labelPositif;
    private javax.swing.JLabel labelUsaha;
    private javax.swing.JPanel panelAkurasi;
    private javax.swing.JPanel panelGerakan;
    private javax.swing.JPanel panelKecepatan;
    private javax.swing.JPanel panelKehalusan;
    private javax.swing.JPanel panelKenyamanan;
    private javax.swing.JPanel panelKeseluruhan;
    private javax.swing.JPanel panelUsaha;
    private javax.swing.JRadioButton radioButtonAkurasi1;
    private javax.swing.JRadioButton radioButtonAkurasi2;
    private javax.swing.JRadioButton radioButtonAkurasi3;
    private javax.swing.JRadioButton radioButtonAkurasi4;
    private javax.swing.JRadioButton radioButtonAkurasi5;
    private javax.swing.JRadioButton radioButtonAkurasi6;
    private javax.swing.JRadioButton radioButtonAkurasi7;
    private javax.swing.JRadioButton radioButtonGerakan1;
    private javax.swing.JRadioButton radioButtonGerakan2;
    private javax.swing.JRadioButton radioButtonGerakan3;
    private javax.swing.JRadioButton radioButtonGerakan4;
    private javax.swing.JRadioButton radioButtonGerakan5;
    private javax.swing.JRadioButton radioButtonGerakan6;
    private javax.swing.JRadioButton radioButtonGerakan7;
    private javax.swing.JRadioButton radioButtonKecepatan1;
    private javax.swing.JRadioButton radioButtonKecepatan2;
    private javax.swing.JRadioButton radioButtonKecepatan3;
    private javax.swing.JRadioButton radioButtonKecepatan4;
    private javax.swing.JRadioButton radioButtonKecepatan5;
    private javax.swing.JRadioButton radioButtonKecepatan6;
    private javax.swing.JRadioButton radioButtonKecepatan7;
    private javax.swing.JRadioButton radioButtonKehalusan1;
    private javax.swing.JRadioButton radioButtonKehalusan2;
    private javax.swing.JRadioButton radioButtonKehalusan3;
    private javax.swing.JRadioButton radioButtonKehalusan4;
    private javax.swing.JRadioButton radioButtonKehalusan5;
    private javax.swing.JRadioButton radioButtonKehalusan6;
    private javax.swing.JRadioButton radioButtonKehalusan7;
    private javax.swing.JRadioButton radioButtonKenyamanan1;
    private javax.swing.JRadioButton radioButtonKenyamanan2;
    private javax.swing.JRadioButton radioButtonKenyamanan3;
    private javax.swing.JRadioButton radioButtonKenyamanan4;
    private javax.swing.JRadioButton radioButtonKenyamanan5;
    private javax.swing.JRadioButton radioButtonKenyamanan6;
    private javax.swing.JRadioButton radioButtonKenyamanan7;
    private javax.swing.JRadioButton radioButtonKeseluruhan1;
    private javax.swing.JRadioButton radioButtonKeseluruhan2;
    private javax.swing.JRadioButton radioButtonKeseluruhan3;
    private javax.swing.JRadioButton radioButtonKeseluruhan4;
    private javax.swing.JRadioButton radioButtonKeseluruhan5;
    private javax.swing.JRadioButton radioButtonKeseluruhan6;
    private javax.swing.JRadioButton radioButtonKeseluruhan7;
    private javax.swing.JRadioButton radioButtonUsaha1;
    private javax.swing.JRadioButton radioButtonUsaha2;
    private javax.swing.JRadioButton radioButtonUsaha3;
    private javax.swing.JRadioButton radioButtonUsaha4;
    private javax.swing.JRadioButton radioButtonUsaha5;
    private javax.swing.JRadioButton radioButtonUsaha6;
    private javax.swing.JRadioButton radioButtonUsaha7;
    // End of variables declaration//GEN-END:variables
}
