/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tappingtest;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author wawan
 */
public class FrameIndependen extends javax.swing.JDialog {

    public String name;
    public String mode;
    public String blok;
    public String trial;
    /**
     * Creates new form FrameIndependen
     */
    public FrameIndependen() {
        initComponents();
        this.setTitle("Independen Form");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupActuation = new javax.swing.ButtonGroup();
        buttonGroupSmooth = new javax.swing.ButtonGroup();
        buttonGroupEffort = new javax.swing.ButtonGroup();
        buttonGroupAccuracy = new javax.swing.ButtonGroup();
        buttonGroupSpeed = new javax.swing.ButtonGroup();
        buttonGroupGeneral = new javax.swing.ButtonGroup();
        buttonGroupOverall = new javax.swing.ButtonGroup();
        buttonGroupFinger = new javax.swing.ButtonGroup();
        buttonGroupWrist = new javax.swing.ButtonGroup();
        buttonGroupArm = new javax.swing.ButtonGroup();
        buttonGroupShoulder = new javax.swing.ButtonGroup();
        buttonGroupNeck = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNegatif = new javax.swing.JLabel();
        labelPositif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonFinger1 = new javax.swing.JRadioButton();
        jRadioButtonFinger2 = new javax.swing.JRadioButton();
        jRadioButtonFinger4 = new javax.swing.JRadioButton();
        jRadioButtonFinger3 = new javax.swing.JRadioButton();
        jRadioButtonFinger6 = new javax.swing.JRadioButton();
        jRadioButtonFinger5 = new javax.swing.JRadioButton();
        jRadioButtonFinger7 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonWrist1 = new javax.swing.JRadioButton();
        jRadioButtonWrist2 = new javax.swing.JRadioButton();
        jRadioButtonWrist3 = new javax.swing.JRadioButton();
        jRadioButtonWrist4 = new javax.swing.JRadioButton();
        jRadioButtonWrist5 = new javax.swing.JRadioButton();
        jRadioButtonWrist6 = new javax.swing.JRadioButton();
        jRadioButtonWrist7 = new javax.swing.JRadioButton();
        jRadioButtonArm1 = new javax.swing.JRadioButton();
        jRadioButtonArm2 = new javax.swing.JRadioButton();
        jRadioButtonArm3 = new javax.swing.JRadioButton();
        jRadioButtonArm4 = new javax.swing.JRadioButton();
        jRadioButtonArm5 = new javax.swing.JRadioButton();
        jRadioButtonArm6 = new javax.swing.JRadioButton();
        jRadioButtonArm7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonShoulder1 = new javax.swing.JRadioButton();
        jRadioButtonShoulder2 = new javax.swing.JRadioButton();
        jRadioButtonShoulder3 = new javax.swing.JRadioButton();
        jRadioButtonShoulder4 = new javax.swing.JRadioButton();
        jRadioButtonShoulder5 = new javax.swing.JRadioButton();
        jRadioButtonShoulder6 = new javax.swing.JRadioButton();
        jRadioButtonShoulder7 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonNeck6 = new javax.swing.JRadioButton();
        jRadioButtonNeck7 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonNeck1 = new javax.swing.JRadioButton();
        jRadioButtonNeck2 = new javax.swing.JRadioButton();
        jRadioButtonNeck3 = new javax.swing.JRadioButton();
        jRadioButtonNeck4 = new javax.swing.JRadioButton();
        jRadioButtonNeck5 = new javax.swing.JRadioButton();
        jRadioButtonActuation1 = new javax.swing.JRadioButton();
        jRadioButtonActuation2 = new javax.swing.JRadioButton();
        jRadioButtonActuation3 = new javax.swing.JRadioButton();
        jRadioButtonActuation4 = new javax.swing.JRadioButton();
        jRadioButtonActuation5 = new javax.swing.JRadioButton();
        jRadioButtonActuation6 = new javax.swing.JRadioButton();
        jRadioButtonActuation7 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonSmooth1 = new javax.swing.JRadioButton();
        jRadioButtonSmooth2 = new javax.swing.JRadioButton();
        jRadioButtonSmooth3 = new javax.swing.JRadioButton();
        jRadioButtonSmooth4 = new javax.swing.JRadioButton();
        jRadioButtonSmooth5 = new javax.swing.JRadioButton();
        jRadioButtonSmooth6 = new javax.swing.JRadioButton();
        jRadioButtonSmooth7 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonEffort6 = new javax.swing.JRadioButton();
        jRadioButtonEffort7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonEffort1 = new javax.swing.JRadioButton();
        jRadioButtonEffort2 = new javax.swing.JRadioButton();
        jRadioButtonEffort3 = new javax.swing.JRadioButton();
        jRadioButtonEffort4 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonEffort5 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonAccuracy1 = new javax.swing.JRadioButton();
        jRadioButtonAccuracy2 = new javax.swing.JRadioButton();
        jRadioButtonAccuracy3 = new javax.swing.JRadioButton();
        jRadioButtonAccuracy4 = new javax.swing.JRadioButton();
        jRadioButtonAccuracy5 = new javax.swing.JRadioButton();
        jRadioButtonAccuracy6 = new javax.swing.JRadioButton();
        jRadioButtonAccuracy7 = new javax.swing.JRadioButton();
        jRadioButtonSpeed1 = new javax.swing.JRadioButton();
        jRadioButtonSpeed2 = new javax.swing.JRadioButton();
        jRadioButtonSpeed3 = new javax.swing.JRadioButton();
        jRadioButtonSpeed4 = new javax.swing.JRadioButton();
        jRadioButtonSpeed5 = new javax.swing.JRadioButton();
        jRadioButtonSpeed6 = new javax.swing.JRadioButton();
        jRadioButtonSpeed7 = new javax.swing.JRadioButton();
        jRadioButtonGeneral6 = new javax.swing.JRadioButton();
        jRadioButtonGeneral7 = new javax.swing.JRadioButton();
        jRadioButtonGeneral1 = new javax.swing.JRadioButton();
        jRadioButtonGeneral2 = new javax.swing.JRadioButton();
        jRadioButtonGeneral3 = new javax.swing.JRadioButton();
        jRadioButtonGeneral4 = new javax.swing.JRadioButton();
        jRadioButtonGeneral5 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonOverall6 = new javax.swing.JRadioButton();
        jRadioButtonOverall7 = new javax.swing.JRadioButton();
        jRadioButtonOverall1 = new javax.swing.JRadioButton();
        jRadioButtonOverall2 = new javax.swing.JRadioButton();
        jRadioButtonOverall3 = new javax.swing.JRadioButton();
        jRadioButtonOverall4 = new javax.swing.JRadioButton();
        jRadioButtonOverall5 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        labelNegatif.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelNegatif.setText("Negatif");

        labelPositif.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelPositif.setText("Positif");

        jLabel1.setText("Finger Fatigue");

        jRadioButtonFinger1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger1);
        jRadioButtonFinger1.setSelected(true);
        jRadioButtonFinger1.setText("1");

        jRadioButtonFinger2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger2);
        jRadioButtonFinger2.setText("2");

        jRadioButtonFinger4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger4);
        jRadioButtonFinger4.setText("4");

        jRadioButtonFinger3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger3);
        jRadioButtonFinger3.setText("3");

        jRadioButtonFinger6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger6);
        jRadioButtonFinger6.setText("6");

        jRadioButtonFinger5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger5);
        jRadioButtonFinger5.setText("5");

        jRadioButtonFinger7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupFinger.add(jRadioButtonFinger7);
        jRadioButtonFinger7.setText("7");

        jLabel2.setText("Wrist Fatigue");

        jRadioButtonWrist1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist1);
        jRadioButtonWrist1.setSelected(true);
        jRadioButtonWrist1.setText("1");

        jRadioButtonWrist2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist2);
        jRadioButtonWrist2.setText("2");

        jRadioButtonWrist3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist3);
        jRadioButtonWrist3.setText("3");

        jRadioButtonWrist4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist4);
        jRadioButtonWrist4.setText("4");

        jRadioButtonWrist5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist5);
        jRadioButtonWrist5.setText("5");

        jRadioButtonWrist6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist6);
        jRadioButtonWrist6.setText("6");

        jRadioButtonWrist7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupWrist.add(jRadioButtonWrist7);
        jRadioButtonWrist7.setText("7");

        jRadioButtonArm1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm1);
        jRadioButtonArm1.setSelected(true);
        jRadioButtonArm1.setText("1");

        jRadioButtonArm2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm2);
        jRadioButtonArm2.setText("2");

        jRadioButtonArm3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm3);
        jRadioButtonArm3.setText("3");

        jRadioButtonArm4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm4);
        jRadioButtonArm4.setText("4");

        jRadioButtonArm5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm5);
        jRadioButtonArm5.setText("5");

        jRadioButtonArm6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm6);
        jRadioButtonArm6.setText("6");

        jRadioButtonArm7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupArm.add(jRadioButtonArm7);
        jRadioButtonArm7.setText("7");

        jLabel3.setText("Arm Fatigue");

        jRadioButtonShoulder1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder1);
        jRadioButtonShoulder1.setSelected(true);
        jRadioButtonShoulder1.setText("1");

        jRadioButtonShoulder2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder2);
        jRadioButtonShoulder2.setText("2");

        jRadioButtonShoulder3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder3);
        jRadioButtonShoulder3.setText("3");

        jRadioButtonShoulder4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder4);
        jRadioButtonShoulder4.setText("4");

        jRadioButtonShoulder5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder5);
        jRadioButtonShoulder5.setText("5");

        jRadioButtonShoulder6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder6);
        jRadioButtonShoulder6.setText("6");

        jRadioButtonShoulder7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupShoulder.add(jRadioButtonShoulder7);
        jRadioButtonShoulder7.setText("7");

        jLabel4.setText("Shoulder Fatigue");

        jRadioButtonNeck6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck6);
        jRadioButtonNeck6.setText("6");

        jRadioButtonNeck7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck7);
        jRadioButtonNeck7.setText("7");

        jLabel5.setText("Neck Fatigue");

        jRadioButtonNeck1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck1);
        jRadioButtonNeck1.setSelected(true);
        jRadioButtonNeck1.setText("1");

        jRadioButtonNeck2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck2);
        jRadioButtonNeck2.setText("2");

        jRadioButtonNeck3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck3);
        jRadioButtonNeck3.setText("3");

        jRadioButtonNeck4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck4);
        jRadioButtonNeck4.setText("4");

        jRadioButtonNeck5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupNeck.add(jRadioButtonNeck5);
        jRadioButtonNeck5.setText("5");

        jRadioButtonActuation1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation1);
        jRadioButtonActuation1.setSelected(true);
        jRadioButtonActuation1.setText("1");

        jRadioButtonActuation2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation2);
        jRadioButtonActuation2.setText("2");

        jRadioButtonActuation3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation3);
        jRadioButtonActuation3.setText("3");

        jRadioButtonActuation4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation4);
        jRadioButtonActuation4.setText("4");

        jRadioButtonActuation5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation5);
        jRadioButtonActuation5.setText("5");

        jRadioButtonActuation6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation6);
        jRadioButtonActuation6.setText("6");

        jRadioButtonActuation7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupActuation.add(jRadioButtonActuation7);
        jRadioButtonActuation7.setText("7");

        jLabel6.setText("Effort");

        jRadioButtonSmooth1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth1);
        jRadioButtonSmooth1.setSelected(true);
        jRadioButtonSmooth1.setText("1");

        jRadioButtonSmooth2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth2);
        jRadioButtonSmooth2.setText("2");

        jRadioButtonSmooth3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth3);
        jRadioButtonSmooth3.setText("3");

        jRadioButtonSmooth4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth4);
        jRadioButtonSmooth4.setText("4");

        jRadioButtonSmooth5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth5);
        jRadioButtonSmooth5.setText("5");

        jRadioButtonSmooth6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth6);
        jRadioButtonSmooth6.setText("6");

        jRadioButtonSmooth7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSmooth.add(jRadioButtonSmooth7);
        jRadioButtonSmooth7.setText("7");

        jLabel7.setText("Accuracy");

        jRadioButtonEffort6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort6);
        jRadioButtonEffort6.setText("6");

        jRadioButtonEffort7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort7);
        jRadioButtonEffort7.setText("7");

        jLabel8.setText("Speed");

        jRadioButtonEffort1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort1);
        jRadioButtonEffort1.setSelected(true);
        jRadioButtonEffort1.setText("1");

        jRadioButtonEffort2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort2);
        jRadioButtonEffort2.setText("2");

        jRadioButtonEffort3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort3);
        jRadioButtonEffort3.setText("3");

        jRadioButtonEffort4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort4);
        jRadioButtonEffort4.setText("4");

        jLabel9.setText("Actuation Force");

        jRadioButtonEffort5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupEffort.add(jRadioButtonEffort5);
        jRadioButtonEffort5.setText("5");

        jLabel10.setText("Smoothness");

        jRadioButtonAccuracy1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy1);
        jRadioButtonAccuracy1.setSelected(true);
        jRadioButtonAccuracy1.setText("1");

        jRadioButtonAccuracy2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy2);
        jRadioButtonAccuracy2.setText("2");

        jRadioButtonAccuracy3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy3);
        jRadioButtonAccuracy3.setText("3");

        jRadioButtonAccuracy4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy4);
        jRadioButtonAccuracy4.setText("4");

        jRadioButtonAccuracy5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy5);
        jRadioButtonAccuracy5.setText("5");

        jRadioButtonAccuracy6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy6);
        jRadioButtonAccuracy6.setText("6");

        jRadioButtonAccuracy7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupAccuracy.add(jRadioButtonAccuracy7);
        jRadioButtonAccuracy7.setText("7");

        jRadioButtonSpeed1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed1);
        jRadioButtonSpeed1.setSelected(true);
        jRadioButtonSpeed1.setText("1");

        jRadioButtonSpeed2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed2);
        jRadioButtonSpeed2.setText("2");

        jRadioButtonSpeed3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed3);
        jRadioButtonSpeed3.setText("3");

        jRadioButtonSpeed4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed4);
        jRadioButtonSpeed4.setText("4");

        jRadioButtonSpeed5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed5);
        jRadioButtonSpeed5.setText("5");

        jRadioButtonSpeed6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed6);
        jRadioButtonSpeed6.setText("6");

        jRadioButtonSpeed7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupSpeed.add(jRadioButtonSpeed7);
        jRadioButtonSpeed7.setText("7");

        jRadioButtonGeneral6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral6);
        jRadioButtonGeneral6.setText("6");

        jRadioButtonGeneral7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral7);
        jRadioButtonGeneral7.setText("7");

        jRadioButtonGeneral1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral1);
        jRadioButtonGeneral1.setSelected(true);
        jRadioButtonGeneral1.setText("1");

        jRadioButtonGeneral2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral2);
        jRadioButtonGeneral2.setText("2");

        jRadioButtonGeneral3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral3);
        jRadioButtonGeneral3.setText("3");

        jRadioButtonGeneral4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral4);
        jRadioButtonGeneral4.setText("4");

        jRadioButtonGeneral5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupGeneral.add(jRadioButtonGeneral5);
        jRadioButtonGeneral5.setText("5");

        jLabel11.setText("General Comfort");

        jRadioButtonOverall6.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall6);
        jRadioButtonOverall6.setText("6");

        jRadioButtonOverall7.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall7);
        jRadioButtonOverall7.setText("7");

        jRadioButtonOverall1.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall1);
        jRadioButtonOverall1.setSelected(true);
        jRadioButtonOverall1.setText("1");

        jRadioButtonOverall2.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall2);
        jRadioButtonOverall2.setText("2");

        jRadioButtonOverall3.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall3);
        jRadioButtonOverall3.setText("3");

        jRadioButtonOverall4.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall4);
        jRadioButtonOverall4.setText("4");

        jRadioButtonOverall5.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroupOverall.add(jRadioButtonOverall5);
        jRadioButtonOverall5.setText("5");

        jLabel12.setText("Overall Operation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonOverall1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOverall2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOverall3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOverall4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOverall5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOverall6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOverall7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonGeneral1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGeneral2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGeneral3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGeneral4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGeneral5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGeneral6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGeneral7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSpeed1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSpeed2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSpeed3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSpeed4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSpeed5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSpeed6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSpeed7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAccuracy1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAccuracy2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAccuracy3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAccuracy4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAccuracy5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAccuracy6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonAccuracy7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonEffort1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEffort2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEffort3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEffort4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEffort5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEffort6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEffort7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSmooth1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSmooth2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSmooth3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSmooth4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSmooth5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSmooth6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSmooth7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonActuation1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonActuation2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonActuation3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonActuation4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonActuation5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonActuation6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonActuation7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonFinger1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFinger2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFinger3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFinger4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFinger5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFinger6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFinger7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonWrist1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWrist2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWrist3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWrist4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWrist5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWrist6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonWrist7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonArm1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonArm2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonArm3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonArm4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonArm5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonArm6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonArm7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonShoulder1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonShoulder2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonShoulder3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonShoulder4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonShoulder5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonShoulder6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonShoulder7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonNeck1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNeck2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNeck3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNeck4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNeck5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNeck6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNeck7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(labelNegatif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPositif)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNegatif)
                    .addComponent(labelPositif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonActuation1)
                    .addComponent(jRadioButtonActuation2)
                    .addComponent(jRadioButtonActuation3)
                    .addComponent(jRadioButtonActuation4)
                    .addComponent(jRadioButtonActuation5)
                    .addComponent(jRadioButtonActuation6)
                    .addComponent(jRadioButtonActuation7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSmooth1)
                    .addComponent(jRadioButtonSmooth2)
                    .addComponent(jRadioButtonSmooth3)
                    .addComponent(jRadioButtonSmooth4)
                    .addComponent(jRadioButtonSmooth5)
                    .addComponent(jRadioButtonSmooth6)
                    .addComponent(jRadioButtonSmooth7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEffort1)
                    .addComponent(jRadioButtonEffort2)
                    .addComponent(jRadioButtonEffort3)
                    .addComponent(jRadioButtonEffort4)
                    .addComponent(jRadioButtonEffort5)
                    .addComponent(jRadioButtonEffort6)
                    .addComponent(jRadioButtonEffort7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAccuracy1)
                    .addComponent(jRadioButtonAccuracy2)
                    .addComponent(jRadioButtonAccuracy3)
                    .addComponent(jRadioButtonAccuracy4)
                    .addComponent(jRadioButtonAccuracy5)
                    .addComponent(jRadioButtonAccuracy6)
                    .addComponent(jRadioButtonAccuracy7)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSpeed1)
                    .addComponent(jRadioButtonSpeed2)
                    .addComponent(jRadioButtonSpeed3)
                    .addComponent(jRadioButtonSpeed4)
                    .addComponent(jRadioButtonSpeed5)
                    .addComponent(jRadioButtonSpeed6)
                    .addComponent(jRadioButtonSpeed7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGeneral1)
                    .addComponent(jRadioButtonGeneral2)
                    .addComponent(jRadioButtonGeneral3)
                    .addComponent(jRadioButtonGeneral4)
                    .addComponent(jRadioButtonGeneral5)
                    .addComponent(jRadioButtonGeneral6)
                    .addComponent(jRadioButtonGeneral7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOverall1)
                    .addComponent(jRadioButtonOverall2)
                    .addComponent(jRadioButtonOverall3)
                    .addComponent(jRadioButtonOverall4)
                    .addComponent(jRadioButtonOverall5)
                    .addComponent(jRadioButtonOverall6)
                    .addComponent(jRadioButtonOverall7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFinger1)
                    .addComponent(jRadioButtonFinger2)
                    .addComponent(jRadioButtonFinger3)
                    .addComponent(jRadioButtonFinger4)
                    .addComponent(jRadioButtonFinger5)
                    .addComponent(jRadioButtonFinger6)
                    .addComponent(jRadioButtonFinger7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonWrist1)
                    .addComponent(jRadioButtonWrist2)
                    .addComponent(jRadioButtonWrist3)
                    .addComponent(jRadioButtonWrist4)
                    .addComponent(jRadioButtonWrist5)
                    .addComponent(jRadioButtonWrist6)
                    .addComponent(jRadioButtonWrist7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonArm1)
                    .addComponent(jRadioButtonArm2)
                    .addComponent(jRadioButtonArm3)
                    .addComponent(jRadioButtonArm4)
                    .addComponent(jRadioButtonArm5)
                    .addComponent(jRadioButtonArm6)
                    .addComponent(jRadioButtonArm7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonShoulder1)
                    .addComponent(jRadioButtonShoulder2)
                    .addComponent(jRadioButtonShoulder3)
                    .addComponent(jRadioButtonShoulder4)
                    .addComponent(jRadioButtonShoulder5)
                    .addComponent(jRadioButtonShoulder6)
                    .addComponent(jRadioButtonShoulder7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNeck1)
                    .addComponent(jRadioButtonNeck2)
                    .addComponent(jRadioButtonNeck3)
                    .addComponent(jRadioButtonNeck4)
                    .addComponent(jRadioButtonNeck5)
                    .addComponent(jRadioButtonNeck6)
                    .addComponent(jRadioButtonNeck7)
                    .addComponent(jLabel5))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelJudul.setText("Independen");
        labelJudul.setToolTipText("");
        labelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        jRadioButtonActuation1.setActionCommand("1");
        jRadioButtonActuation2.setActionCommand("2");
        jRadioButtonActuation3.setActionCommand("3");
        jRadioButtonActuation4.setActionCommand("4");
        jRadioButtonActuation5.setActionCommand("5");
        jRadioButtonActuation6.setActionCommand("6");
        jRadioButtonActuation7.setActionCommand("7");
        jRadioButtonSmooth1.setActionCommand("1");
        jRadioButtonSmooth2.setActionCommand("2");
        jRadioButtonSmooth3.setActionCommand("3");
        jRadioButtonSmooth4.setActionCommand("4");
        jRadioButtonSmooth5.setActionCommand("5");
        jRadioButtonSmooth6.setActionCommand("6");
        jRadioButtonSmooth7.setActionCommand("7");
        jRadioButtonEffort1.setActionCommand("1");
        jRadioButtonEffort2.setActionCommand("2");
        jRadioButtonEffort3.setActionCommand("3");
        jRadioButtonEffort4.setActionCommand("4");
        jRadioButtonEffort5.setActionCommand("5");
        jRadioButtonEffort6.setActionCommand("6");
        jRadioButtonEffort7.setActionCommand("7");
        jRadioButtonAccuracy1.setActionCommand("1");
        jRadioButtonAccuracy2.setActionCommand("2");
        jRadioButtonAccuracy3.setActionCommand("3");
        jRadioButtonAccuracy4.setActionCommand("4");
        jRadioButtonAccuracy5.setActionCommand("5");
        jRadioButtonAccuracy6.setActionCommand("6");
        jRadioButtonAccuracy7.setActionCommand("7");
        jRadioButtonSpeed1.setActionCommand("1");
        jRadioButtonSpeed2.setActionCommand("2");
        jRadioButtonSpeed3.setActionCommand("3");
        jRadioButtonSpeed4.setActionCommand("4");
        jRadioButtonSpeed5.setActionCommand("5");
        jRadioButtonSpeed6.setActionCommand("6");
        jRadioButtonSpeed7.setActionCommand("7");
        jRadioButtonGeneral1.setActionCommand("1");
        jRadioButtonGeneral2.setActionCommand("2");
        jRadioButtonGeneral3.setActionCommand("3");
        jRadioButtonGeneral4.setActionCommand("4");
        jRadioButtonGeneral5.setActionCommand("5");
        jRadioButtonGeneral6.setActionCommand("6");
        jRadioButtonGeneral7.setActionCommand("7");
        jRadioButtonOverall1.setActionCommand("1");
        jRadioButtonOverall2.setActionCommand("2");
        jRadioButtonOverall3.setActionCommand("3");
        jRadioButtonOverall4.setActionCommand("4");
        jRadioButtonOverall5.setActionCommand("5");
        jRadioButtonOverall6.setActionCommand("6");
        jRadioButtonOverall7.setActionCommand("7");
        jRadioButtonFinger1.setActionCommand("1");
        jRadioButtonFinger2.setActionCommand("2");
        jRadioButtonFinger3.setActionCommand("3");
        jRadioButtonFinger4.setActionCommand("4");
        jRadioButtonFinger5.setActionCommand("5");
        jRadioButtonFinger6.setActionCommand("6");
        jRadioButtonFinger7.setActionCommand("7");
        jRadioButtonWrist1.setActionCommand("1");
        jRadioButtonWrist2.setActionCommand("2");
        jRadioButtonWrist3.setActionCommand("3");
        jRadioButtonWrist4.setActionCommand("4");
        jRadioButtonWrist5.setActionCommand("5");
        jRadioButtonWrist6.setActionCommand("6");
        jRadioButtonWrist7.setActionCommand("7");
        jRadioButtonArm1.setActionCommand("1");
        jRadioButtonArm2.setActionCommand("2");
        jRadioButtonArm3.setActionCommand("3");
        jRadioButtonArm4.setActionCommand("4");
        jRadioButtonArm5.setActionCommand("5");
        jRadioButtonArm6.setActionCommand("6");
        jRadioButtonArm7.setActionCommand("7");
        jRadioButtonShoulder1.setActionCommand("1");
        jRadioButtonShoulder2.setActionCommand("2");
        jRadioButtonShoulder3.setActionCommand("3");
        jRadioButtonShoulder4.setActionCommand("4");
        jRadioButtonShoulder5.setActionCommand("5");
        jRadioButtonShoulder6.setActionCommand("6");
        jRadioButtonShoulder7.setActionCommand("7");
        jRadioButtonNeck1.setActionCommand("1");
        jRadioButtonNeck2.setActionCommand("2");
        jRadioButtonNeck3.setActionCommand("3");
        jRadioButtonNeck4.setActionCommand("4");
        jRadioButtonNeck5.setActionCommand("5");
        jRadioButtonNeck6.setActionCommand("6");
        jRadioButtonNeck7.setActionCommand("7");
        
        try {
            // TODO add your handling code here:
            PrintWriter pw = new PrintWriter(new File("Form Independen "+name+"_"+mode+"_"+blok+"_"+trial+".csv"));
            StringBuilder sb = new StringBuilder();
            sb.append("Actuation Force, Operation Smoothness, Operation Effort, Accuracy, Operation Speed, General Comfort, "
                    + "Overall Operation, Finger Fatigue, Wrist Fatigue, Arm Fatigue, Shoulder Fatigue, Neck Fatigue \n");
            sb.append(buttonGroupActuation.getSelection().getActionCommand()+",");
            sb.append(buttonGroupSmooth.getSelection().getActionCommand()+",");
            sb.append(buttonGroupEffort.getSelection().getActionCommand()+",");
            sb.append(buttonGroupAccuracy.getSelection().getActionCommand()+",");
            sb.append(buttonGroupSpeed.getSelection().getActionCommand()+",");
            sb.append(buttonGroupGeneral.getSelection().getActionCommand()+",");
            sb.append(buttonGroupOverall.getSelection().getActionCommand()+",");
            sb.append(buttonGroupFinger.getSelection().getActionCommand()+",");
            sb.append(buttonGroupWrist.getSelection().getActionCommand()+",");
            sb.append(buttonGroupArm.getSelection().getActionCommand()+",");
            sb.append(buttonGroupShoulder.getSelection().getActionCommand()+",");
            sb.append(buttonGroupNeck.getSelection().getActionCommand()+"\n");
            pw.write(sb.toString());
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Save");
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIndependen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIndependen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIndependen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIndependen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIndependen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAccuracy;
    private javax.swing.ButtonGroup buttonGroupActuation;
    private javax.swing.ButtonGroup buttonGroupArm;
    private javax.swing.ButtonGroup buttonGroupEffort;
    private javax.swing.ButtonGroup buttonGroupFinger;
    private javax.swing.ButtonGroup buttonGroupGeneral;
    private javax.swing.ButtonGroup buttonGroupNeck;
    private javax.swing.ButtonGroup buttonGroupOverall;
    private javax.swing.ButtonGroup buttonGroupShoulder;
    private javax.swing.ButtonGroup buttonGroupSmooth;
    private javax.swing.ButtonGroup buttonGroupSpeed;
    private javax.swing.ButtonGroup buttonGroupWrist;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAccuracy1;
    private javax.swing.JRadioButton jRadioButtonAccuracy2;
    private javax.swing.JRadioButton jRadioButtonAccuracy3;
    private javax.swing.JRadioButton jRadioButtonAccuracy4;
    private javax.swing.JRadioButton jRadioButtonAccuracy5;
    private javax.swing.JRadioButton jRadioButtonAccuracy6;
    private javax.swing.JRadioButton jRadioButtonAccuracy7;
    private javax.swing.JRadioButton jRadioButtonActuation1;
    private javax.swing.JRadioButton jRadioButtonActuation2;
    private javax.swing.JRadioButton jRadioButtonActuation3;
    private javax.swing.JRadioButton jRadioButtonActuation4;
    private javax.swing.JRadioButton jRadioButtonActuation5;
    private javax.swing.JRadioButton jRadioButtonActuation6;
    private javax.swing.JRadioButton jRadioButtonActuation7;
    private javax.swing.JRadioButton jRadioButtonArm1;
    private javax.swing.JRadioButton jRadioButtonArm2;
    private javax.swing.JRadioButton jRadioButtonArm3;
    private javax.swing.JRadioButton jRadioButtonArm4;
    private javax.swing.JRadioButton jRadioButtonArm5;
    private javax.swing.JRadioButton jRadioButtonArm6;
    private javax.swing.JRadioButton jRadioButtonArm7;
    private javax.swing.JRadioButton jRadioButtonEffort1;
    private javax.swing.JRadioButton jRadioButtonEffort2;
    private javax.swing.JRadioButton jRadioButtonEffort3;
    private javax.swing.JRadioButton jRadioButtonEffort4;
    private javax.swing.JRadioButton jRadioButtonEffort5;
    private javax.swing.JRadioButton jRadioButtonEffort6;
    private javax.swing.JRadioButton jRadioButtonEffort7;
    private javax.swing.JRadioButton jRadioButtonFinger1;
    private javax.swing.JRadioButton jRadioButtonFinger2;
    private javax.swing.JRadioButton jRadioButtonFinger3;
    private javax.swing.JRadioButton jRadioButtonFinger4;
    private javax.swing.JRadioButton jRadioButtonFinger5;
    private javax.swing.JRadioButton jRadioButtonFinger6;
    private javax.swing.JRadioButton jRadioButtonFinger7;
    private javax.swing.JRadioButton jRadioButtonGeneral1;
    private javax.swing.JRadioButton jRadioButtonGeneral2;
    private javax.swing.JRadioButton jRadioButtonGeneral3;
    private javax.swing.JRadioButton jRadioButtonGeneral4;
    private javax.swing.JRadioButton jRadioButtonGeneral5;
    private javax.swing.JRadioButton jRadioButtonGeneral6;
    private javax.swing.JRadioButton jRadioButtonGeneral7;
    private javax.swing.JRadioButton jRadioButtonNeck1;
    private javax.swing.JRadioButton jRadioButtonNeck2;
    private javax.swing.JRadioButton jRadioButtonNeck3;
    private javax.swing.JRadioButton jRadioButtonNeck4;
    private javax.swing.JRadioButton jRadioButtonNeck5;
    private javax.swing.JRadioButton jRadioButtonNeck6;
    private javax.swing.JRadioButton jRadioButtonNeck7;
    private javax.swing.JRadioButton jRadioButtonOverall1;
    private javax.swing.JRadioButton jRadioButtonOverall2;
    private javax.swing.JRadioButton jRadioButtonOverall3;
    private javax.swing.JRadioButton jRadioButtonOverall4;
    private javax.swing.JRadioButton jRadioButtonOverall5;
    private javax.swing.JRadioButton jRadioButtonOverall6;
    private javax.swing.JRadioButton jRadioButtonOverall7;
    private javax.swing.JRadioButton jRadioButtonShoulder1;
    private javax.swing.JRadioButton jRadioButtonShoulder2;
    private javax.swing.JRadioButton jRadioButtonShoulder3;
    private javax.swing.JRadioButton jRadioButtonShoulder4;
    private javax.swing.JRadioButton jRadioButtonShoulder5;
    private javax.swing.JRadioButton jRadioButtonShoulder6;
    private javax.swing.JRadioButton jRadioButtonShoulder7;
    private javax.swing.JRadioButton jRadioButtonSmooth1;
    private javax.swing.JRadioButton jRadioButtonSmooth2;
    private javax.swing.JRadioButton jRadioButtonSmooth3;
    private javax.swing.JRadioButton jRadioButtonSmooth4;
    private javax.swing.JRadioButton jRadioButtonSmooth5;
    private javax.swing.JRadioButton jRadioButtonSmooth6;
    private javax.swing.JRadioButton jRadioButtonSmooth7;
    private javax.swing.JRadioButton jRadioButtonSpeed1;
    private javax.swing.JRadioButton jRadioButtonSpeed2;
    private javax.swing.JRadioButton jRadioButtonSpeed3;
    private javax.swing.JRadioButton jRadioButtonSpeed4;
    private javax.swing.JRadioButton jRadioButtonSpeed5;
    private javax.swing.JRadioButton jRadioButtonSpeed6;
    private javax.swing.JRadioButton jRadioButtonSpeed7;
    private javax.swing.JRadioButton jRadioButtonWrist1;
    private javax.swing.JRadioButton jRadioButtonWrist2;
    private javax.swing.JRadioButton jRadioButtonWrist3;
    private javax.swing.JRadioButton jRadioButtonWrist4;
    private javax.swing.JRadioButton jRadioButtonWrist5;
    private javax.swing.JRadioButton jRadioButtonWrist6;
    private javax.swing.JRadioButton jRadioButtonWrist7;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelNegatif;
    private javax.swing.JLabel labelPositif;
    // End of variables declaration//GEN-END:variables
}
